---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adopter-service
  namespace: microservices
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api/v1/adopters
spec:
  ingressClassName: alb
  rules:
    - host: ding.dogadoptioncenter.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adopter-service
                port:
                  number: 8080
